### ISSUE TITLE
CI: need to install `rustfmt-nightly`?

### ISSUE THREAD

**Issue by ErichDonGubler** [rjs-team/rjs#17]
If we could confirm that `rustfmt-nightly` and NOT stable's `rustfmt` is actually being used, then I'd be more than happy to remove another line of code.

**Comment by ricochet1k** [comment]
rustfmt and cargo-fmt are broken in the current nightly, but rustfmt-nightly still works. Rustfmt-nightly isn't strictly necessary, but it is definitely helpful to avoid build failures due to broken nightly.
