### ISSUE TITLE
Fix Appveyor

### ISSUE THREAD

**Issue by ricochet1k** [rjs-team/rjs#19]
Just going to throw a few things down here:

- `make` needs to be installed
- `python2` probably needs to be installed as well, since it isn't mentioned in the config file?
- rust-mozjs has an [appveyor.yml file here](https://github.com/servo/rust-mozjs/blob/master/appveyor.yml), perhaps we should steal some of that?

**Comment by ErichDonGubler** [comment]
Looks like we'll need CMake also?

**Comment by ricochet1k** [comment]
Thanks @sagudev
