### ISSUE TITLE
Adding Dependencies

### ISSUE THREAD

**Issue by WolfieWerewolf** [rjs-team/rjs#29]
Hi guys.. I noticed in your tickets that you have referenced Servo for dependencies such as WebSockets etc.... The "simple example" that I'm attempting to port over is proving to be a little more complicated than I expected because it uses textures and therefore needs to load images.  I'm keen to see if I can make it work and noticed that Servo uses this library for their HTMLImageElement.
https://github.com/PistonDevelopers/image
Unless you have any objections I'll follow this pattern (borrowing dependencies from Servo or use what they use)..  It's published as a crate so I should be able to just add it to the cargo.toml..

Of course if rjs ever supports native node.js modules this kind of thing could be re-factored into an external library... I've seen some decent examples for writing native node modules in rust..

Kind Regards
/W

**Comment by ricochet1k** [comment]
Go for it, that sounds like a great idea.

My general plan in adding these kinds of libraries is expose the simplest interface to JS that is useful, and then write JS code to fake things like the HTMLImageElement. So I'm thinking, some kind of "readImage" or "readImageSync" function that simply returns the pixels in an ArrayBuffer. Ideally it would be a zero copy conversion, but I don't think that's realistic right now.

Let me know if you get stuck with the ArrayBuffer conversion. Servo doesn't have good documentation, but I've spent a lot of time digging into it, so I should be able to help.

**Comment by ricochet1k** [comment]
Let's move discussions like this to https://gitter.im/rjs-team/Lobby and leave issues for actual issues/feature-requests.
